name : Deploy to Vercel

on:
    push:
        branches:
            - main
        paths:
             - 'apps/frontend/**'
jobs :
    deploy :
        runs-on: ubuntu-latest

        steps:
            - name : checkout code
              uses: action/checkout@v3


            - name: Setup Node.js
              uses: action/setup-node@v3
              with:
                node-version : 22
                cache : "npm"
            
            - name : Install dependencies
              working-directory : apps/frontend
              run : npm install
            
            - name : Build Project
              working-directory : apps/frontend
              run : npm run dev

            - name : "Deploy to Vercel"
              env :
                VERCEL_TOKEN : ${{secrets.VERCEL_TOKEN}}
              working-directory : apps/frontend
              run : npx vercel --prod

