name: Deploy Next.js to Vercel

on:
  push:
    branches:
      - main
    paths:
      - 'apps/frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Ensure lock file exists
        working-directory: apps/frontend
        run: |
          if [ ! -f package-lock.json ]; then
            echo "Error: package-lock.json is missing."
            exit 1
          fi

      - name: Install dependencies
        working-directory: apps/frontend
        run: npm ci

      - name: Build project
        working-directory: apps/frontend
        run: npm run build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        working-directory: apps/frontend
        run: npx vercel --prod
